### ISSUE TITLE
Empty sample file

### ISSUE THREAD

**Issue by Teketel** [Koodous/Scripts#3]
Running the following script should download zipped sample file, but the downloaded zip has empty `sample` file.
`curl -g -O -J -L -H "Authorization: Token MY_TOKEN" https://api.koodous.com/feed/apks`

**Comment by plutec** [comment]
Do you have premium account? https://docs.koodous.com/feed/apks/

**Comment by Teketel** [comment]
@plutec
Yes, I have premium account, and I am using premium account token.

**Comment by plutec** [comment]
Contact with Koodous ppl then.
